services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"   # Interface web Jenkins
      - "50000:50000" # Port JNLP pour agents Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home   # Persistance des données Jenkins
      - /var/run/docker.sock:/var/run/docker.sock  # Accès au Docker hôte (optionnel)
      - ./projet:/home/projet             # Dossier partagé Mac ↔ conteneur Ubuntu
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Désactive le wizard initial (optionnel)
    networks:
      - ci_network

volumes:
  jenkins_home:
    driver: local

networks:
  ci_network:
    driver: bridge
